# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.4

before_script:
  - bash tests/install.sh > /dev/null
  - composer global require phpunit/phpunit 7.*
  - composer global require squizlabs/php_codesniffer
  - composer global require phpcompatibility/php-compatibility
  - /root/.composer/vendor/bin/phpcs --config-set installed_paths /root/.composer/vendor/phpcompatibility/php-compatibility

job1:
  script:
    - phpunit --configuration tests/phpunit.xml --coverage-text --colors=never

job2:
  script:
    - /root/.composer/vendor/bin/phpcs --standard=tests/.phpcs.xml
