on:
  push:
    branches:
      - main
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build, push, and verify image
        env:
          RELEVANT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          echo ${{ secrets.PACKAGES_TOKEN }} | docker login docker.pkg.github.com -u ces-khanhhoang --password-stdin
          docker build --tag docker.pkg.github.com/ces-khanhhoang/drupal10-test:version$RELEVANT_SHA .
          docker push docker.pkg.github.com/ces-khanhhoang/drupal10-test:version$RELEVANT_SHA
          docker pull docker.pkg.github.com/ces-khanhhoang/drupal10-test:version$RELEVANT_SHA
