name: Create and push Docker image to package

on:
  release:
    types: [published]
  push:
    tags:
      - prod.*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Get the commit SHA for the tag
        id: get_commit
        run: echo "::set-output name=commit_sha::$(git rev-list -n 1 ${{ github.ref }})"

      - name: Get the branch name containing the commit
        id: get_branch
        run: |
          COMMIT_SHA="${{ steps.get_commit.outputs.commit_sha }}"
          BRANCH_NAME=$(git branch -r --contains "$COMMIT_SHA" | grep -v '\->' | grep 'origin/' | head -n 1 | sed 's|origin/||')
          echo "Branch name: $BRANCH_NAME"
          echo "::set-output name=branch_name::$BRANCH_NAME"
      
      - name: Exit if not on main branch
        if: steps.get_branch.outputs.branch_name != 'main'
        run: exit -1
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short

      - name: Build and push Docker image latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.tags }}
