on:
  push:
    branches:
      - main
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build, push, and verify image
        run: |
          echo ${{ secrets.PACKAGES_TOKEN }} | docker login docker.pkg.github.com -u ces-khanhhoang --password-stdin
          docker build --tag docker.pkg.github.com/ces-khanhhoang/drupal10-test:version1.0.0 .
          docker push docker.pkg.github.com/ces-khanhhoang/drupal10-test:version1.0.0
          docker pull docker.pkg.github.com/ces-khanhhoang/drupal10-test:version1.0.0
